// @ts-nocheck
import type { CodegenConfig } from '@graphql-codegen/cli';

const gqlDir = './src/features/graphql';

const config: CodegenConfig = {
  overwrite: true,
  schema: `${gqlDir}/**/schema.graphql`,
  documents: [`${gqlDir}/schemas/*`],
  generates: {
    [`${gqlDir}/codegen/`]: {
      preset: 'client',
      plugins: [
        {
          add: {
            content: [
              '/* eslint-disable */',
              '// @ts-nocheck',
              '/* Code generated by graphql-codegen. DO NOT EDIT. */',
            ],
          },
        },
        // 'typescript',
        // 'typescript-operations',
        'typescript-urql',
      ],
    },
  },
  hooks: {
    afterOneFileWrite: ['prettier --write'],
  },
  DocumentMode: 'documentNodeImportFragments',
};

export default config;
